### ISSUE TITLE
Modelo-2.0.4 - sorting stages list by "last accessed" doesn't appear to make a difference

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1095]
when i try to sort the stages list by "last accessed", it does not change the list and the stage that i just entered doesn't appear at the top.

**Comment by teddyfullstack** [comment]
Actually, the sorter "prioritised" another column (creation date) over this column (last accessed) since we have multi-sort criteria. Just cancel sorting on the left column(s), and it will work as you desire 👇 

<img width="1352" alt="Screenshot 2023-09-23 at 22 58 17" src="https://github.com/upstage-org/upstage/assets/29925961/af23e663-e9e7-4ac5-a337-e8e90682e15f">

<img width="1354" alt="Screenshot 2023-09-23 at 22 58 27" src="https://github.com/upstage-org/upstage/assets/29925961/9b0e8027-c236-4aab-99a4-bb9555c0ebb4">
