### ISSUE TITLE
Modelo-2.0.4. - Demo stage default set-up

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1101]
previously we have asked there be a generic selection of media pre-installed and assigned to the Demo stage in all new instances (see https://github.com/upstage-org/upstage/issues/898).
currently on dev-app (Modelo-2.0.4.) there was no media at all on the Demo stage.

it should also be default to assign all new players (on approval of accounts) as players on the Demo stage.

**Comment by helenvarley** [comment]
could this be prioritised? it's quite time-consuming to re-assign the default media to the demo stage, & it's important to have it there when we're showing new people how things work.

**Comment by teddyfullstack** [comment]
Hi @helenvarley, I've just executed the scaffold script to create the stock Demo stage, and you can still access the old demo stage as "Legacy Demo Stage" 👇 

![Image](https://github.com/upstage-org/upstage/assets/29925961/fe0b1e67-354c-4122-bcb2-f74521cc7a4b)

Please let me know if the intention of this issue is fulfilled, thank you 😅

**Comment by helenvarley** [comment]
Great! that all looks good :smile: & i see that all the players are added with player & edit access - excellent! thank you :smile:

**Comment by gloriajw** [comment]
@teddyfullstack Please leave detailed instructions on what you ran, and what dependencies it has (where it expects to find default assets, etc). Thank you!

**Comment by helenvarley** [comment]
i'm reopening this as on the updated upstage.mur.at there was no media, nothing on the demo stage & no media in the studio. i've just manually uploaded the media as i need it on tuesday, but ideally this should all be there in a new install.

**Comment by teddyfullstack** [comment]
I ran the scaffold script after the new install, and it worked fine. Maybe you didn't see it because the default filter only shows your media (the demo media was uploaded under my account). The media is still there, you can see it in the Date column 👇 

<img width="1438" alt="Screenshot 2023-11-19 at 14 53 30" src="https://github.com/upstage-org/upstage/assets/29925961/08e00aeb-7a6e-4c5a-ae60-bec230abb20a">

**Comment by helenvarley** [comment]
ah ok - i think i was just looking too soon :laughing:
