### ISSUE TITLE
error message when deleting a player

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#1276]
i'm trying to delete the player James from upstage.live, as there is no email address attached to the account and it's a previous dev who isn't working on UpStage anymore. however, when i try to delete the account i get this error message:

![Screenshot from 2024-05-15 10:04:11](https://github.com/upstage-org/upstage/assets/3437324/dab8ba7a-564b-46a5-b22a-9e2d943f6148)

just before this i successfully deleted another player account that didn't have an email address attached to it, so it's not that the delete function isn't working. 

i thought it could be because the player James is an Admin. the other player i deleted was just a Player. i tried to change James' role to Player, but got the message "Email required!" - so i entered a dummy email and was then able to change the role to Player. then i tried deleting the account again - but got the same error message.

**Comment by helenvarley** [comment]
as far as i can see, there are no stages or media items owned by this player account.

**Comment by vickis** [comment]
I just went to replicate this - deactivated the account and got the all media will become yours message
<img width="1272" alt="Screen Shot 2024-06-06 at 9 34 03 AM" src="https://github.com/upstage-org/upstage/assets/4249450/82e0ac45-4c9e-4e54-bfa8-cc4a5dc024b7">
but then as Helen observed the next step is an error saying media is owned ...

To my nonDev eyes it appears the issue is that James has a scene saved somewhere - i just went to search through scenes for old stages and got this is the stages preview

**Comment by vickis** [comment]
I went through manually and found a stage by James (also deleted a few test stages that were over 2 years old) mission accomplished 
<img width="1268" alt="image" src="https://github.com/upstage-org/upstage/assets/4249450/1705f065-73bf-4d65-a0df-a36786b0bc0b">
<img width="1268" alt="image" src="https://github.com/upstage-org/upstage/assets/4249450/1705f065-73bf-4d65-a0df-a36786b0bc0b">
