### ISSUE TITLE
Media: Browsing compatibility 

### ISSUE THREAD

**Issue by riadsalameh** [upstage-org/upstage#252]
It doesn't seem like I am able to upload any media when I am using Safari

**Comment by nguyenhongphat0** [comment]
Hi Riad, can you describe more about the issue you are facing (did you see any error message, or you got stuck at any step?). I'm also using Safari and media upload is working for me. There is a video for instruction how to upload media, it's too large to attach on Github so I post it on Slack 😅

**Comment by nguyenhongphat0** [comment]
Ah I found a way to compress the video, you don't have to find it on Slack anymore, Riad: 
https://user-images.githubusercontent.com/29925961/114207202-507d7a00-9986-11eb-9117-d5a6e14a13f2.mov

**Comment by riadsalameh** [comment]
Nothing happens whenever I try to upload any file but when I choose the same files through google chrome. it works perfectly. 

https://user-images.githubusercontent.com/71765608/114208964-637c5400-995e-11eb-8f3d-85f005fac969.mov

**Comment by nguyenhongphat0** [comment]
Thank you Riad, I'll check this. And can you send me that file via Slack?

**Comment by riadsalameh** [comment]
The video file??

**Comment by nguyenhongphat0** [comment]
Okay to sum up, we got 2 issues with Browser compatibility:
1. Upload media on Safari 13. After inspecting I figure that it there was a bug with Safari 13 that not trigger onChange event on file input. This got fixed when you upgrade to Safari 14. In R2-2021 we will have a new UI for upload/edit media, which will focus on drag/drop and multiple file selections (a demo of what it would look like: https://www.dropzonejs.com/#), and looks like will better support Safari 13
<img width="1310" alt="Screenshot 2021-04-14 at 14 51 53" src="https://user-images.githubusercontent.com/29925961/114673965-f5a2a480-9d30-11eb-88c5-caa67b42d563.png">

2. Players who use Firefox will stuck at Connecting, unless they open `about:config`, and change `network.http.spdy.websockets` to `false`. This is a known bug of mosquitto and firefox: https://github.com/eclipse/mosquitto/issues/1211, so in UpStage we only have few choices:
- Show a warning on Firefox if they stuck at Connecting for too long (an instruction to change the about:config)
- Encourage our users to use Chrome/Chromium
- Use http instead of https (until the bug got fixed on Firefox)

**Comment by helenvarley** [comment]
is this just on mobile devices? or everyone using firefox? i remember that i had to do change the websocket thing with the first demo stage, so maybe i have no problems because it's already changed.

using http instead of https - is this a choice that we can make from our end? or something that we need to instruct individuals to do?

and does this only affect players, or audience as well?

**Comment by nguyenhongphat0** [comment]
> is this just on mobile devices? or everyone using firefox?

It will happen will everyone using Firefox. But once the config already changed, it's works correctly like other browsers

> using http instead of https - is this a choice that we can make from our end? or something that we need to instruct individuals to do?

If we have partners install UpStage on their own server, they will be the one who decide to use `http` or `https`. Using `https` is considering secure, but will add an extra overhead to the `mqtt` protocol (https://github.com/eclipse/mosquitto/issues/1211#issuecomment-819307610)

> and does this only affect players, or audience as well?

It will affects both players and audience (because they use the same mqtt connection)

**Comment by nguyenhongphat0** [comment]
Although using https add an overhead to the mqtt, we still need `https` for the streaming to work (a webcam can only be accessed if the content is served via HTTPS)

**Comment by vickis** [comment]
I suggest that as upgrading to newer browser works for Safari
and _should_ eventually get fixed for Firefox (seeing as it is a known
issue) that in the interim
- we document what needs to happen to allow UpStage to work (if have to use
these or older browsers)
- but suggest using Chrome et al

we previously had to advise about downloading flash and throwing effort at
issues which might hopefully become obsolete with the release of new
versions of browsers seems counterproductive

i think using https is important, obviously for streaming but also for
security

thanks for the clear explanations @Nguyen Hong Phat ***@***.***>
 :)

**Comment by helenvarley** [comment]
is it possible to have a help message come up when a browser gets stuck on connecting, with a link to a page on the UpStage website where we can keep an updated list of common browser problems? then it would be easy to update as browser development solves some issues (and no doubt introduces new ones ... ) and the page could include tips such as trying other browsers or any other tips to solve common problems.
this page could then also be accessible from other hosted instances of UpStage, so that for example a university with their own instance would not have to provide this information separately themselves.

**Comment by vickis** [comment]
agree :) - very useful to keep all this information together (and will be
helpful in running workshops and introductions for new users)

**Comment by elisadcg** [comment]
Where we put this information on the manual ? I put it in Technical information chapter right now :)

**Comment by vickis** [comment]
Agree
Listing optimum browsers per OS as we know them
In a. Ideal world UpStage would work on everything - but compatible with
most common is next best situation :)

**Comment by helenvarley** [comment]
> Where we put this information on the manual ? I put it in Technical information chapter right now :)

yes - for now; but we'll need to separate out things like browser info that is useful for players and audience to find, from information about installing an UpStage server (that's currently on the tech page) - since this will confuse some people, they might think they need to install the server to participate.

maybe a "trouble-shooting" section? as that might be a more logical place to look for people having access issues, or small tech problems during performances.

**Comment by vickis** [comment]
agree :)

**Comment by nguyenhongphat0** [comment]
> Upload media on Safari 13... we will have a new UI for upload/edit media, which will focus on drag/drop and multiple file selections (a demo of what it would look like: https://www.dropzonejs.com/#)

It's the UpStage Studio that I've promised, and it works with Safari 14+ as I can tell 🧭
