### ISSUE TITLE
customisable backstage landing page

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#331]
After logging in, it would be nice to arrive at a customisable backstage landing page, that could have information for players such as upcoming events, audition notices, anything specific to that instance of UpStage e.g. who to contact for help or other interesting things.

**Comment by nguyenhongphat0** [comment]
Wow your skill on opening issue is soo good, Helen 🤣

**Comment by helenvarley** [comment]
i'm practising a lot! :sunglasses:

**Comment by vickis** [comment]
yes agree - useful :)

**Comment by vickis** [comment]
Perhaps something like a link added to the top navigation and identifies if changes have been made since your last visit ?  (eg like the private chat function onstage  - called noticeboard  or info ...

it could then host the information suggested

**Comment by teddyfullstack** [comment]
I'm trying to clean up issues to make the "to-do list" more obvious 😅 I'm starting with issues with the `backstage` tag first since most of the problems are no longer needed because we have the Studio now.

If you need to have the Studio "customisable", let's make a new issue since the discussion above doesn't cope anymore!

**Comment by helenvarley** [comment]
sure - this is totally a "nice to have" not a "must have"! :smile:
