### ISSUE TITLE
pop-out icon on stream - not needed

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#580]
i just noticed that there is a pop-out icon on streams - that i can click on, and the stream opens in a separate window, away from the stage. this is not really something that we need or want.
it is not there for audience (at least not in chromium on linux) so it's a very minor thing, but it would be good to remove it if possible as it's unnecessary & maybe confusing for some players.
![Screenshot from 2021-09-23 16:09:36](https://user-images.githubusercontent.com/3437324/134523204-d968ff1a-2f85-4c40-9ebb-a54abfa1c323.png)

**Comment by nguyenhongphat0** [comment]
Wow! Which user you are using, Helen?

**Comment by helenvarley** [comment]
i'm logged in as me, helen
in firefox on linux

**Comment by nguyenhongphat0** [comment]
This is another browser feature, called Picture in Picture, which allow you to "pin" a playing video to a floating window so that can still watch it while doing something else. For example:

| UpStage | Somewhere else |
|-|-|
|<img width="1390" alt="Screenshot 2021-09-24 at 19 55 46" src="https://user-images.githubusercontent.com/29925961/134677708-f3533bf8-16e3-4203-b4c3-74650eaac8fd.png">|<img width="1339" alt="Screenshot 2021-09-24 at 19 55 20" src="https://user-images.githubusercontent.com/29925961/134677727-f91a4a43-f2b5-4e78-8798-8c2346ae557b.png">|

We can programatically prevent this control in other browsers, unfortunately Firefox browser `explicitly don't want to restrict the user in what videos they can open in Picture-in-Picture` (read their full comment here: https://bugzilla.mozilla.org/show_bug.cgi?id=1611831#c5), so the only way to turn it off is user have to this themselves by changing the Firefox settings:

![image](https://user-images.githubusercontent.com/29925961/134678696-f00610d0-b203-4528-b55b-85df482ceede.png)

I don't think we need to instruct our users to do this as well, since it is more like a feature than a bug, and pretty cool isn't it 😆

**Comment by helenvarley** [comment]
ok, interesting! i guess we should not be trying to stop it. my main concern is whether it happens also for audience. i thought that it did not, as i entered the stage as audience from another browser; but now i tried it & see that as audience in Firefox, i also see this icon.
this is really not good, as audience could make the stream pop out & then would see something like this on the stage, which is not what the artists will want:
![Screenshot from 2021-09-24 16:38:45](https://user-images.githubusercontent.com/3437324/134693278-1a2ca356-845e-4c1d-9555-9d6d6c2d231b.png)

**Comment by helenvarley** [comment]
but ... it is probably something we just have to live with; it's certainly not a high priority for solving before the launch. 
unfortunately, it's now the second reason why firefox is not the best browser for UpStage :(

**Comment by nguyenhongphat0** [comment]
Firefox will show that button without acknowledge of whether you are a player or an audiences. But from what I experienced, that button won't show if your frame size is small enough. However, I believe if user can enable Picture in Picture mode by clicking that button, they will be able to exit that mode by pressing the X button 😅

**Comment by vickis** [comment]
I agree
Add to  trouble shooting documentation (how to avoid)
if it’s tricky to restrict or us  having to describe what not to do in a
performance

It’s interesting and possibly something artists might want to use also
Give audience some agency ;)

Recommending avoiding Firefox (or rather suggesting a performance is best
watched in chrome might be the easier solution right now :)

**Comment by helenvarley** [comment]
not sure how useful it is when it's only something that Firefox users have?
let's just not worry about it, and as you say recommend chrome / chromium as the better browser to use

**Comment by vickis** [comment]
For sure :)
