### ISSUE TITLE
freaky multiframe backdrop bug - URGENT!

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#654]
during the festival there has been some random weirdness with multiframe backdrops that has been difficult to precisely describe.
now i did a test, with a new stage. i assigned 3 backdrops, one is a multiframe backdrop with 2 frames in it.
when i select this backdrop, i get random flashes of other backdrops that are not even assigned to this stage.
THIS IS URGENT ... 
![backdrop_bug](https://user-images.githubusercontent.com/3437324/137599926-38c9c0d2-7fb0-4816-8807-a5fc6b032521.gif)
.

**Comment by helenvarley** [comment]
the stage that this is happening on is https://upstage.live/V4.0/ui/live/MoDemoJam

**Comment by helenvarley** [comment]
every time i go back to the media page in the stage management, nothing is assigned ...
this is a big problem as i have asked the artists to assign the media they want to use in our jam tomorrow, to this stage. but it seems that every time someone will go to add their media, it will remove all the media already assigned to the stage ...

**Comment by vickis** [comment]
I have tried removing the multiframe backdrop that appeared to be causing the issue  -  saved and swept and re-assigned the backdrop to the stage 
![image](https://user-images.githubusercontent.com/4249450/137606266-83252ce5-f3b1-481d-8127-e19c2dfceed7.png)

i think the issue was me trying to save the scene with the multi-frame animating ... it appears to be working over on the jam stage now (as in no ghost images of the tideway multi-frame are showing

**Comment by vickis** [comment]
This issue is happening again 
- assigning new media (backdrops) is causing other media, previously assigned to disappear

**Comment by nguyenhongphat0** [comment]
> assigning new media (backdrops) is causing other media, previously assigned to disappear

I think it should go into issue #655, this URGENT issue is about the multi-frame backdrop glitching on stage while switching scene!

**Comment by vickis** [comment]
apologies you are right Phat!

**Comment by nguyenhongphat0** [comment]
Nah it's okay. Just so many issues so I want to keep them as unique as possible 😅
