### ISSUE TITLE
Statistic during Stage on Tablet render problems

### ISSUE THREAD

**Issue by elisadcg** [upstage-org/upstage#664]
During the Festival. I use my tablet to see the Stage. I "touch" on the Statistic, and it open it and then 2 problems :
- no scroll bar, and the list was more longer than i can see
- when i touch it back, the statistic doesn't closed :-(. So I stuck. I reload and not touch anymore the statistic information !

**Comment by nguyenhongphat0** [comment]
I didn't notice that the players list doesn't have a scrollbar because most of the time I'm doing the development, there was only me in the list 🤣 Here you go 👇 

<img width="354" alt="Screenshot 2021-11-02 at 22 36 58" src="https://user-images.githubusercontent.com/29925961/139882438-d0dacf02-6d50-445c-9083-160aac956ad9.png">

> when i touch it back, the statistic doesn't closed

I cannot re-produce this case, however I have rewritten the logic of the statistic's visibility. Let me know if you still facing the issue 🙏

**Comment by vickis** [comment]
Ha ha you (plural) and a few friends!
Thanks you all :D

**Comment by helenvarley** [comment]
great; we can test this on 27th november when some of the performances will be performed again :) (& hopefully lots of people in the audience!)
