### ISSUE TITLE
system configuration

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#678]
this part of the Admin section, https://upstage.live/backstage/admin/system-configurations has only a link to the documentation plan ... what should be here?

should there be something here for customising the Foyer page, or is that all taken care of directly in the Foyer?

**Comment by nguyenhongphat0** [comment]
Foyer customisation is taken care of directly in the Foyer, as designed in #325 

What should be here usually the system configuration, such as streaming server, mqtt password,... But considering these things should be attached to the code, because I afraid admins can broke things by changing them accidentally. At the moment, Term of service is the only thing that live there 😆

**Comment by helenvarley** [comment]
ok. and only admins should have access to customising the foyer, right? normal players should not be able to do this.

@paul-rohrlach @gloriajw @vickis - what things should admins be able to configure from this interface? i would say the streaming server, since this will need to be set up for each instance and should not require changing the code (i think?)

the terms of service are presumably what new registrations have to read and agree to, so it's important that this is customisable by admins (& we need to do this too!)

anything else?

**Comment by nguyenhongphat0** [comment]
> should there be something here for customising the Foyer page

Yes and we have that now 😆

**Comment by vickis** [comment]
:D bless you Phat!
