### ISSUE TITLE
for one player only, stage was offline

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#697]
we had a curious thing on http://meta.upstage.live - of 7 people who connected to UpStage, one was always only offline on the stage. he could access the backstage, and enter the stage, and see what was happening there, but not interact, and the status showed offline.

- he was on mac os 10.15.7, and tried with safari, firefox and chrome - same in all browsers: he was logged in, could access backstage. but on the stage he was offline.
- he was at Meta Theater, so on the same network as another player who was on the live stage no problem and interacting, so it wasn't a firewall or network issue.
- another in the group was also using mac 10.15.7. and safari, and she had no problems.

any idea what might have been the problem???

he's going to try again when he is at home & will let me know if it's still a problem.

**Comment by gloriajw** [comment]
Please let me know what happens when he's home, and also ask him to note what is IP address is (type "what is my ip" in duck duck go). This will help me find his traffic. I can't think of anything offhand that would block mqtt on a personal computer or browser session, but it does sound like this is what's happening.

**Comment by nguyenhongphat0** [comment]
I'd gone into the same problem once, turn out it was AdBlock Plus disabled my API because the endpoint was end with `/ad` :cold_face: In this case he tried multiple browsers, so I guess it wasn't AdBlock. It could be some other software installed on his machine, anti-virus software could also be it. But please give us the IP and more information if you can, thank you :pray:

**Comment by helenvarley** [comment]
yes - if it's an adblocker he must have it installed on all 3 browsers - which is of course possible. i've asked him for his IP & he's also going to let me know if it still happens when he's at home. if it does, then it must be something on his laptop!

**Comment by helenvarley** [comment]
sebastian just wrote that he is back at home & UpStage is live and working in all of his browsers - which is good, but sheds no light on the mystery!
