### ISSUE TITLE
safari issue for streams?

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#705]
today two people who were both on safari could hear but not see the streams. everyone else could see it, altho some who had the stage open in 2 browser windows were only seeing it in one. i think that must be a bandwidth issue (we had zoom running as well).
the two safari users are both on  10.15.7 and i think safari 15.
@vickis do you have safari?

**Comment by vickis** [comment]
i do have safari - but do not really use it - its an old version ...

i use chrome for UpStage and other things
and firefox often (but avoid for UpStage that because of the known issues...

I thought we would have to up our current server capacity to host more
streams (as we noticed also in Mo-Demo the issues with multiple streams
jamming the stage (if some users had multiple windows and 2? streams each -
using zoom and into upstage then i am not surprised there was some issues

would be great to know what the bandwidth possibilities/number of
streams/cams etc ratio really is ....
especially for creating the 'business models' for hosting...

**Comment by helenvarley** [comment]
bandwidth is a separate issue - this is about whether there is a specific problem with safari. i'm meeting sebastian on wednesday to do some more testing & looking at OBS settings, & we will try again with safari. if he still can't see the stream in safari, we should find a few other people who can also try it in safari & then put a note in the troubleshooting chapter of the manual about it.

for bandwidth - see discussion on slack about looking at different protocols. but mostly the issues are local - individual's computer capacity and/or internet connections - & we can't do much about that other than try to optimise the speed-to-quality ratio of streams.

**Comment by helenvarley** [comment]
closing this as i don't know if there's still a safari issue, but anyway there are other issues to do with people not receiving streams.
