### ISSUE TITLE
object drawing: not possible to resize before light bulb turned on

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#717]
it's not possible to resize an object drawing before the light bulb is turned on. you can move the frame, but the image does not resize until you turn on the light bulb so you can't see if you've got the size right. and, you cannot make it smaller. if you make the frame smaller, then the drawing is obstructing the light bulb so that you cannot turn it on.
(i tried in both firefox and chromium, same problem in both)
![objectdrawing_resize](https://user-images.githubusercontent.com/3437324/146403069-454e1d27-9944-40a3-b22e-0834b0469091.gif)

**Comment by vickis** [comment]
huh - i had not noticed that
it is like the drawing has no relation to the frame

when the 'canvas' is active and you are making the drawing it covers almost
all of the stage (you can find the edges if you draw around) so when the
drawing is saved the frame is decided by the external parameters of the
drawing

i guess what is happening there is that as the drawing (in its frame) is
added to the stage then it is needing to be switched to active of rany
changes to take place (because notice the drawing is not resizing up with
the frame either until switched on)

it is awhile now since i was creating multiple of things and most recently
i have used live drawing (Repose)
good to explore

**Comment by helenvarley** [comment]
you can do everything except resize before turning on the light bulb - if you move the drawing to another place on the stage, rotate, flip, or change its opacity, you see all of these things happening with the B&W image before you turn the light bulb on. it is only the resizing that you don't see until you turn the light bulb on.

**Comment by helenvarley** [comment]
this is sort of working, but not really: when i increase the size of the object drawing before turning on the lightbulb, the size does not change until i turn on the lightbulb. the audience sees the object being drawn and increasing in size at the same time.
