### ISSUE TITLE
show hide avatar name

### ISSUE THREAD

**Issue by vickis** [upstage-org/upstage#9]
as a user i should be able to toggle between visible and invisible for the name appended to the avatar

**Comment by helenvarley** [comment]
currently the avatar names don't show on the stage at all. do we want them to?

**Comment by elisadcg** [comment]
it's up to artist :) in theater or in animation : we did not see the name of the character

**Comment by helenvarley** [comment]
we had it previously in UpStage, & it is a feature from graphical chatrooms, but in fact i would mostly hide the name in shows & it was sometimes distracting if people forgot or didn't know.
so let's have the default is that it's not visible on the stage, but in the future develop the option to show it? this could be included in the pop-up for changing the nickname - a toggle to show it on stage, that is by default off.

**Comment by nguyenhongphat0** [comment]
I remember saw an issue about remove that grey icon above avatar. But I think that icon is what we need to resolve this issue 🤔 

<img width="1401" alt="Screenshot 2021-04-09 at 23 02 08" src="https://user-images.githubusercontent.com/29925961/114208431-aacb0a80-9987-11eb-898e-46ba97e67404.png">

Did I miss something?

**Comment by helenvarley** [comment]
the other issue is #247 - that the audience should not see the revolving icon over the avatars' heads. this issue is about whether or not the avatar name is visible to everyone (audience and players) on the stage. previously in UpStage, the avatar's name was displayed underneath the avatar, and we could hide it if we wanted to.
if we were to have the avatar names displayed on stage in the new UpStage, they could not be over the avatar as this is where the speech bubble appears. 

for now, this is a very very low priority issue. we may find that we don't really need to show the names - we can use the options that elisa suggested above. or if we decide we really do need it, then we can see later how to add it in.
