### ISSUE TITLE
"Hide from Stage List" button now a bit confusing ...

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#901]
i realised that now that we have the Visibility toggle, to show or hide a stage on the Foyer, the "Hide from Stage List" button is a bit confusing. 
i think it would make more sense to have this also as a toggle, either next to or under the foyer one, so that both are together in the "Visibilty" section of the Stage Management interface.
the text for this toggle should say "Select whether this Stage is visible in the Backstage Stages List or not."
then i think it's clear - one toggle makes the stage publicly visible on the Foyer, the other is about visibility to other players in the Backstage.
this will also make that top bar a bit tidier & more consistent with others, as at the moment it's pretty crowded.

![Screenshot from 2022-04-26 12:59:54](https://user-images.githubusercontent.com/3437324/165286401-e1ac799d-7886-408e-9665-bf2994429060.png)

**Comment by nguyenhongphat0** [comment]
Actually I think the `Hide From Stage List` button is what the `Visibility Toggle` would have been 🤔 I created that button a long time ago from @elisadcg Wireframe, and until now it is just a static button, without any action on being clicked.

I think we should remove this button, because hiding a stage from the stage management list is not really a good idea 😅. We would end up with creating a ghost stage, which we won't be able to access but still exists on our system, taking spaces and resources.

**Comment by vickis** [comment]
I agree remove the button and function
Don’t want ghost stages. :0

if players not assigned they can’t access anyway right :)

**Comment by helenvarley** [comment]
> if players not assigned they can’t access anyway right :)

not at all if it's in rehearsal status, & only as audience if it's live. 

until someone comes up with a situation where hiding a stage from the Backstage list would be useful, we go without it :)
