### ISSUE TITLE
media item on stage that is not assigned to stage or even uploaded to the studio

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/upstage#925]
i saw that dev-app was a blank install again, so i created a stage and assigned a backdrop and an avatar to it. i then entered the stage, and discovered on the stage a prop that i had not assigned to it - and that is not even uploaded to the studio. i had uploaded it previously to dev-app, but there is now only the sample media and my avatar that i uploaded earlier today. i created the stage new just now.

![Peek 2022-05-10 21-34](https://user-images.githubusercontent.com/3437324/167708368-2b07855f-b0c6-425a-894b-d274caa7811c.gif)

**Comment by vickis** [comment]
oooh

**Comment by nguyenhongphat0** [comment]
There used to be a stage with the same url `helen` on `dev-app1`. When it got removed the archived events (live message that was sent over the MQTT broker) is still kept, that's why when you re-create the stage with the same url, you see these media that was put on the deleted stage.

In other words, removing a stage and then create another stage with the same url will keep what is there on the stage (not the media that was assigned). Do you think we could keep this behavior as a feature? 😆If not then I can clear the stage whenever you delete a stage if you would like to 👌

**Comment by vickis** [comment]
Yes to clearing stage when deleting
If it is to be removed then everything associated should also be removed -
this will save confusion and mean a unique name is required (there will be
multiple Helen stages created - so ghosts of past stages turning up is
probably best avoided  :)
